---

version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8989:8989   # Sonarr
      - 7878:7878   # Radarr
      - 8080:8080   # qBittorrent
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8191:8191   # FlareSolverr
      - 9696:9696   # Prowlarr
      - 6969:6969   # Tracker
      - 3579:3579   # Ombi
      - 8083:80     # Heimdall (HTTP)
      - 8443:443    # Heimdall (HTTPS)

    environment: #https://github.com/qdm12/gluetun-wiki/tree/main/setup/providers
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=10.70.230.29/32,fc00:bbbb:bbbb:bb01::7:e61c/128
      - SERVER_COUNTRIES=Switzerland
      - FIREWALL_OUTBOUND_SUBNETS=192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
    restart: always
  flaresolverr:
    image: ghcr.io/thephaseless/byparr:latest
    container_name: flaresolverr
    network_mode: service:gluetun
    environment:
      - LOG_LEVEL=info
    restart: always
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: service:gluetun
    volumes:
      - /docker/appdata/prowlarr:/config
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr 
    network_mode: service:gluetun
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
    - /volume1/data:/data
    - /docker/appdata/sonarr:/config
    restart: always
  whisparr:
    image: ghcr.io/thespad/whisparr:latest
    container_name: whisparr
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /docker/appdata/whisparr:/config
      - /volume1/data:/data
    restart: always    
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: service:gluetun
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Stockholm
    volumes:
    - /docker/appdata/radarr:/config
    - /volume1/data:/data
    restart: always
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /docker/appdata/qbittorrent:/config
      - /volume1/data/torrents:/downloads
    restart: always
  swaparr-radarr:
    image: ghcr.io/thijmengthn/swaparr:latest
    container_name: swaparr-radarr
    network_mode: service:gluetun
    restart: always
    environment:
      - BASEURL=http://127.0.0.1:7878 # IP or FQDN           (Required)
      - APIKEY=${RADARR_API_KEY}      # Radarr API Key       (Required)                
      - PLATFORM=radarr               # "radarr", "sonarr".. (Optional) default: radarr
      - TIME_THRESHOLD=2h             # 1d, 6h, 30m, etc..   (Optional) default: 2h    
      - SIZE_THRESHOLD=25GB           # 1TB, 1GB, 1MB, etc.. (Optional) default: 25GB  
      - CHECK_INTERVAL=10m            # 1d, 6h, 30m, etc..   (Optional) default: 10m   
      - STRIKE_THRESHOLD=3            # Positive number      (Optional) default: 3     
      - AGGRESSIVE_STRIKES=true      # Boolean              (Optional) default: false 

  # -- (Optional)
  swaparr-sonarr: 
    image: ghcr.io/thijmengthn/swaparr:latest
    container_name: swaparr-sonarr
    network_mode: service:gluetun
    restart: always
    environment:
      - BASEURL=http://127.0.0.1:8989 # IP or FQDN           (Required)
      - APIKEY=${SONARR_API_KEY}       # Sonarr API Key       (Required)                
      - PLATFORM=sonarr               # "radarr", "sonarr".. (Optional) default: radarr
      - TIME_THRESHOLD=2h             # 1d, 6h, 30m, etc..   (Optional) default: 2h    
      - SIZE_THRESHOLD=25GB           # 1TB, 1GB, 1MB, etc.. (Optional) default: 25GB  
      - CHECK_INTERVAL=10m            # 1d, 6h, 30m, etc..   (Optional) default: 10m   
      - STRIKE_THRESHOLD=3            # Positive number      (Optional) default: 3     
      - AGGRESSIVE_STRIKES=true      # Boolean              (Optional) default: false

  swaparr-whisparr:
    image: ghcr.io/thijmengthn/swaparr:latest
    container_name: swaparr-whisparr
    network_mode: service:gluetun
    restart: always
    environment:
      - BASEURL=http://127.0.0.1:6969 # Whisparr listens on port 6969
      - APIKEY=${WHISPARR_API_KEY}    # You’ll need to add this in your .env
      - PLATFORM=whisparr             # Platform type
      - TIME_THRESHOLD=2h             # default: 2h
      - SIZE_THRESHOLD=25GB           # default: 25GB
      - CHECK_INTERVAL=10m            # default: 10m
      - STRIKE_THRESHOLD=3            # default: 3
      - AGGRESSIVE_STRIKES=true       # default: false

  plex:
    image: plexinc/pms-docker
    container_name: plex
    environment:
      - TZ=Europe/Stockholm
      - VERSION=docker
      - HOSTNAME=PlexServer
      # - PLEX_CLAIM=claim-xxxx   # optional
      - PLEX_UID=1000
      - PLEX_GID=1000
    volumes:
      - /docker/appdata/plex:/config
      - /volume1/data/media:/data/media
    network_mode: host         # required for discovery/remote access
    privileged: true           # fixes occasional libusb issues
    restart: unless-stopped

  # ombi:
  #   image: lscr.io/linuxserver/ombi:latest
  #   container_name: ombi
  #   network_mode: service:gluetun
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Stockholm
  #   volumes:
  #     - /docker/appdata/ombi:/config
  #   restart: unless-stopped

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /docker/appdata/heimdall:/config
    restart: unless-stopped

  cross-seed:
    image: ghcr.io/cross-seed/cross-seed:latest
    container_name: cross-seed
    network_mode: service:gluetun
    depends_on:
      - prowlarr
      - qbittorrent
    volumes:
      - ./cross-seed:/config
      - /volume1/data:/data          # so it can see your completed files
    environment:
      - TZ=Europe/Stockholm
    command: ["daemon","--config","/config/config.json"]
    restart: unless-stopped
