version: "3.8"

services:
  # gluetun:
  #   image: qmcgaw/gluetun@sha256:29be3ff9a71ecc5ddb6716b5a4859b1af5712a6debe90ca69b100ef784845bbc
  #   container_name: gluetun
  #   cap_add: [NET_ADMIN]
  #   devices:
  #     - /dev/net/tun:/dev/net/tun
  #   sysctls:
  #     - net.ipv6.conf.all.disable_ipv6=0
  #   # Only expose ports that belong to apps that MUST stay in the VPN namespace (qBittorrent)
  #   ports:
  #     - 8080:8080     # qBittorrent UI
  #     # Keep Shadowsocks only if you actually use it:
  #     # - 8388:8388/tcp
  #     # - 8388:8388/udp
  #   environment:
  #     - VPN_SERVICE_PROVIDER=mullvad
  #     - VPN_TYPE=wireguard
  #     - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
  #     - WIREGUARD_ADDRESSES=10.67.106.235/32
  #     - SERVER_COUNTRIES=Sweden
  #     - FIREWALL_OUTBOUND_SUBNETS=192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
  #     - WIREGUARD_ALLOWED_IPS=0.0.0.0/0
  #   restart: always
  #   networks:
  #     - arrnet

  # qbittorrent:
  #   image: lscr.io/linuxserver/qbittorrent:latest
  #   container_name: qbittorrent
  #   network_mode: service:gluetun         # stays behind VPN
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Stockholm
  #   volumes:
  #     - qbittorrent_config:/config
  #     - /volume1/data/torrents:/downloads
  #   restart: always
  #   depends_on:
  #     gluetun:
  #       condition: service_healthy

  # --- Everything below is OFF the VPN (normal bridge) ---

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest@sha256:5379a9209c86870558d77c8cdf7efdf300aecf0447617a05dc77e0491d53f34c
    container_name: flaresolverr
    shm_size: "2gb"
    environment:
      - LOG_LEVEL=info
    restart: always
    networks: [arrnet]
    ports:
      - 8191:8191

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest@sha256:fa81e471a7e46a24b121838563a10d468cf82eecd1587a464c6df4927ecc3248
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - prowlarr_config:/config
    restart: always
    networks: [arrnet]
    ports:
      - 9696:9696

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest@sha256:328d322af2bb8d7211a9c43a26ff5e658ba3e6f47a695e8fb9ff806bfeab0f04
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - sonarr_config:/config
      - /volume1/data:/data
    restart: always
    networks: [arrnet]
    ports:
      - 8989:8989

  whisparr:
    image: ghcr.io/thespad/whisparr:latest@sha256:9efe12d790a7f064b5744db613892fc1ada413688c70ad383243ed0c3e5e2d79
    container_name: whisparr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - whisparr_config:/config
      - /volume1/data:/data
    restart: always
    networks: [arrnet]
    ports:
      - 6969:6969

  radarr:
    image: lscr.io/linuxserver/radarr:latest@sha256:19474a623b278f558c9696a19b84640ad4aff3b2959f08904a77ffbad73ed7bd
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - radarr_config:/config
      - /volume1/data:/data
    restart: always
    networks: [arrnet]
    ports:
      - 7878:7878

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest@sha256:cf7a02a46d37899eeafd1d96b81984168f771f89c554a52a2fd35437fdc16cb6
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - bazarr_config:/config
      - /volume1/data/media:/data/media
    restart: unless-stopped
    networks: [arrnet]
    ports:
      - 6767:6767

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest@sha256:e0761ee4071dcf8f0515d492711f8671c025814dc4976764422185b53ee3778c
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - overseerr_config:/config
    restart: unless-stopped
    networks: [arrnet]
    ports:
      - 5055:5055

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest@sha256:0694415ee12a42b362c291b0f77dc2b42eb4bc0877bda26253c9c8a6d79dab01
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - heimdall_config:/config
    restart: unless-stopped
    networks: [arrnet]
    ports:
      - 8083:80
      - 8443:443

  rclone-seedbox-pull:
    image: rclone/rclone:latest@sha256:d5971950c2b370fb04dd3292541b5bda6d9103143fd7e345aeb435a399388afc
    container_name: rclone-seedbox-pull
    user: "1000:1000"
    restart: unless-stopped
    environment:
      - TZ=Europe/Stockholm
      - RCLONE_CONFIG=/dev/null
      - RCLONE_CONFIG_SEEDBOX_TYPE=sftp
      - RCLONE_CONFIG_SEEDBOX_HOST=137.ftl11.seedit4.me
      - RCLONE_CONFIG_SEEDBOX_PORT=2113
      - RCLONE_CONFIG_SEEDBOX_USER=seedit4me
      - RCLONE_CONFIG_SEEDBOX_PASS=${RCLONE_SEEDBOX_OBSCURED_PASS}
    volumes:
      - /volume1/data:/data
    entrypoint: /bin/sh
    command:
      - -c
      - |
        while :; do
          rclone copy "seedbox:/home/seedit4me/torrents/qbittorrent" "/data/seedbox-sync/qbittorrent" \
            --transfers=4 --checkers=8 --fast-list \
            --exclude="**/*.!qB" --exclude="**/.unwanted/**" --min-age 5m --max-age 180h \
            --copy-links --create-empty-src-dirs \
            --use-json-log --log-level=INFO --stats=30s;
          sleep 300;
        done
    networks: [arrnet]

  unpackerr:
    image: golift/unpackerr:latest@sha256:a9e7eb0d7b0ca16d2bdcb5af52eb4b544053ad6d915dd9b0f8383bc83f1df5cc
    container_name: unpackerr
    user: "1000:1000"
    environment:
      - TZ=Europe/Stockholm
      # Update to service names (no more 127.0.0.1)
      - UN_SONARR_0_URL=http://sonarr:8989
      - UN_SONARR_0_API_KEY=${SONARR_API_KEY}
      - UN_RADARR_0_URL=http://radarr:7878
      - UN_RADARR_0_API_KEY=${RADARR_API_KEY}
      - UN_WHISPARR_0_URL=http://whisparr:6969
      - UN_WHISPARR_0_API_KEY=${WHISPARR_API_KEY}
      - UN_SONARR_0_DELETE_ORIG=false
      - UN_RADARR_0_DELETE_ORIG=false
      - UN_WHISPARR_0_DELETE_ORIG=false
      - UN_FOLDER_0_PATH=/data/torrents
      - UN_FOLDER_0_EXTRACT_PATH=/data/torrents
      - UN_FOLDER_0_DELETE_AFTER=96h
      - UN_FOLDER_1_PATH=/data/seedbox-sync/qbittorrent
      - UN_FOLDER_1_EXTRACT_PATH=/data/seedbox-sync/qbittorrent
      - UN_FOLDER_1_DELETE_AFTER=96h
      - UN_LOG_LEVEL=INFO
    volumes:
      - /volume1/data:/data
    restart: unless-stopped
    networks: [arrnet]
    depends_on:
      sonarr:
        condition: service_started
      radarr:
        condition: service_started
      whisparr:
        condition: service_started

  plex:
    image: plexinc/pms-docker@sha256:4e704a2172129d8a6bc5b05ea201945b329bb6512f48a4e92ed4a4a787c35462
    container_name: plex
    environment:
      - TZ=Europe/Stockholm
      - VERSION=docker
      - HOSTNAME=PlexServer
      - PLEX_UID=1000
      - PLEX_GID=1000
    volumes:
      - plex_config:/config
      - /volume1/data/media:/data/media
    network_mode: host
    privileged: true
    restart: unless-stopped

volumes:
  prowlarr_config:
  sonarr_config:
  radarr_config:
  whisparr_config:
  qbittorrent_config:
  heimdall_config:
  plex_config:
  overseerr_config:
  bazarr_config:

networks:
  arrnet:
    driver: bridge
