---                     
# To get gluetun setup                                                                                                                                                                                                                                                                    
# sudo modprobe tun
# sudo mkdir -p /dev/net
# sudo mknod /dev/net/tun c 10 200
# sudo chmod 600 /dev/net/tun                                                                                                                                                                                                                                                                                            
services:
  gluetun:
    image: qmcgaw/gluetun@sha256:29be3ff9a71ecc5ddb6716b5a4859b1af5712a6debe90ca69b100ef784845bbc
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    ports:
      - 8989:8989     # Sonarr
      - 7878:7878     # Radarr
      - 8080:8080     # qBittorrent
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8191:8191     # FlareSolverr
      - 9696:9696     # Prowlarr
      - 6969:6969     # Whisparr
      - 3579:3579     # Ombi (if enabled)
      - 8083:80       # Heimdall (HTTP)
      - 8443:443      # Heimdall (HTTPS)
      - 5055:5055     # Overseerr
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=10.67.106.235/32
      - SERVER_COUNTRIES=Sweden
      - FIREWALL_OUTBOUND_SUBNETS=192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
      - WIREGUARD_ALLOWED_IPS=0.0.0.0/0
    restart: always

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest@sha256:ab535d1fef5d7f1654c2756949798442ae4bbecee99d4338128aa137fd8eca0e
    container_name: flaresolverr
    network_mode: service:gluetun
    shm_size: "2gb"
    environment:
      - LOG_LEVEL=info
    restart: always
    depends_on:
      gluetun:
        condition: service_healthy

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest@sha256:4f2a6d597845b2f3e19284b1d982b3e0b4bd7c22472c2979c956aa198b83f472
    container_name: prowlarr
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - prowlarr_config:/config
    restart: always
    depends_on:
      gluetun:
        condition: service_healthy

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest@sha256:e00e87e0e7c24fdc992093756f120a6ab292790b6a637ff3641bf813091cd726
    container_name: sonarr
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - sonarr_config:/config
      - /volume1/data:/data
    restart: always
    depends_on:
      gluetun:
        condition: service_healthy

  whisparr:
    image: ghcr.io/thespad/whisparr:latest@sha256:d2641a4934746095bad9df9d28c746795bafb14eff8fc3555b7e00c73607e378
    container_name: whisparr
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - whisparr_config:/config
      - /volume1/data:/data
    restart: always
    depends_on:
      gluetun:
        condition: service_healthy

  radarr:
    image: lscr.io/linuxserver/radarr:latest@sha256:7eb64f5af8bbe48e79bc55c0c37ca8db89b2f073a9ff0094f603916ae1df9de8
    container_name: radarr
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - radarr_config:/config
      - /volume1/data:/data
    restart: always
    depends_on:
      gluetun:
        condition: service_healthy

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest@sha256:ebfd00848045b30298bcb43627e24bd98ff2bbf584d9b3e62257586de85bcb15
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - qbittorrent_config:/config
      - /volume1/data/torrents:/downloads
    restart: always
    depends_on:
      gluetun:
        condition: service_healthy

  swaparr-radarr:
    image: ghcr.io/thijmengthn/swaparr:latest@sha256:1ebd53ac1919ade81c8185c66830d3467ecda7dfde5a383dc9a91fc21e713ba2
    container_name: swaparr-radarr
    network_mode: service:gluetun
    restart: always
    environment:
      - BASEURL=http://127.0.0.1:7878
      - APIKEY=${RADARR_API_KEY}
      - PLATFORM=radarr
      - TIME_THRESHOLD=2h
      - SIZE_THRESHOLD=25GB
      - CHECK_INTERVAL=10m
      - STRIKE_THRESHOLD=3
      - AGGRESSIVE_STRIKES=true
    depends_on:
      gluetun:
        condition: service_healthy

  swaparr-sonarr:
    image: ghcr.io/thijmengthn/swaparr:latest@sha256:1ebd53ac1919ade81c8185c66830d3467ecda7dfde5a383dc9a91fc21e713ba2
    container_name: swaparr-sonarr
    network_mode: service:gluetun
    restart: always
    environment:
      - BASEURL=http://127.0.0.1:8989
      - APIKEY=${SONARR_API_KEY}
      - PLATFORM=sonarr
      - TIME_THRESHOLD=2h
      - SIZE_THRESHOLD=25GB
      - CHECK_INTERVAL=10m
      - STRIKE_THRESHOLD=3
      - AGGRESSIVE_STRIKES=true
    depends_on:
      gluetun:
        condition: service_healthy

  swaparr-whisparr:
    image: ghcr.io/thijmengthn/swaparr:latest@sha256:1ebd53ac1919ade81c8185c66830d3467ecda7dfde5a383dc9a91fc21e713ba2
    container_name: swaparr-whisparr
    network_mode: service:gluetun
    restart: always
    environment:
      - BASEURL=http://127.0.0.1:6969
      - APIKEY=${WHISPARR_API_KEY}
      - PLATFORM=whisparr
      - TIME_THRESHOLD=2h
      - SIZE_THRESHOLD=25GB
      - CHECK_INTERVAL=10m
      - STRIKE_THRESHOLD=3
      - AGGRESSIVE_STRIKES=true
    depends_on:
      gluetun:
        condition: service_healthy

  plex:
    image: plexinc/pms-docker@sha256:4e704a2172129d8a6bc5b05ea201945b329bb6512f48a4e92ed4a4a787c35462
    container_name: plex
    environment:
      - TZ=Europe/Stockholm
      - VERSION=docker
      - HOSTNAME=PlexServer
      - PLEX_UID=1000
      - PLEX_GID=1000
      # - PLEX_CLAIM=claim-xxxx
    volumes:
      - plex_config:/config
      - /volume1/data/media:/data/media
    network_mode: host          # discovery/remote access
    privileged: true            # occasional libusb issues
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest@sha256:1da69e20c9379ee1dc464792876bb83b62d97cdaa63d25cfdbab7138f1109917
    container_name: heimdall
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - heimdall_config:/config
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy

  rclone-seedbox-pull:
    image: rclone/rclone:latest@sha256:fd635aecd9667ee3c3bf920d14118090d4f2a83a080c1fa77e0bafbd4587ca87
    container_name: rclone-seedbox-pull
    user: "1000:1000"
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - TZ=Europe/Stockholm
      - RCLONE_CONFIG=/config/rclone.conf
    volumes:
      - /volume1/data:/data
      - ./rclone:/config  # keep host-managed for easy editing
    entrypoint: /bin/sh
    command:
      - -c
      - |
        while :; do
          rclone copy "seedbox:/home/seedit4me/torrents/qbittorrent" "/data/seedbox-sync/qbittorrent" \
            --transfers=4 --checkers=8 --fast-list \
            --exclude="**/*.!qB" --exclude="**/.unwanted/**" --min-age 5m --max-age 24h \
            --copy-links --create-empty-src-dirs \
            --use-json-log --log-level=INFO --stats=30s;
          sleep 300;
        done
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest@sha256:f0bb47460bfbcf7c31dad8b62e2546fb336b4b5209a8404a23e77100da0f25f7
    container_name: overseerr
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - overseerr_config:/config
    restart: unless-stopped
volumes:
  prowlarr_config:
  sonarr_config:
  radarr_config:
  whisparr_config:
  qbittorrent_config:
  heimdall_config:
  plex_config:
  overseerr_config:
