[seedbox]
type = sftp
host = ftl11.seedit4.me
user = seedit4me
port = 2113
pass = 5YRFQePC42MoblbXA-doasXm4qoJfMLMMg
md5sum_command = none
sha1sum_command = none
shell_type = none
disable_hashcheck = true
known_hosts_file = /config/known_hosts
